version: "2.0"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  flask-simple:
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 app.py
    volumes:
      - ./src:/usr/src/app/

  mongodb:
    image: mongo
    ports:
      - 27018:27017
